DROP TABLE IF EXISTS materiales;

CREATE TABLE materiales (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS tipos;

CREATE TABLE tipos (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS clientes;

CREATE TABLE clientes (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  email VARCHAR(250) NOT NULL,
  confirm_id BIGINT
);

DROP TABLE IF EXISTS productos;

CREATE TABLE productos (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  dire VARCHAR(250) NOT NULL,
  cost DOUBLE,
  description VARCHAR(1000) NOT NULL,
  mat_id BIGINT,
  typ_id BIGINT

);